#!/bin/bash

# 🚀 BANK FILE SCHEDULER - QUICK START GUIDE
# Copy and paste commands below to get up and running

echo "======================================================"
echo "BANK FILE SCHEDULER - QUICK START"
echo "======================================================"
echo ""

# STEP 1: Verify setup
echo "STEP 1️⃣ : VERIFY SCHEDULER WORKS"
echo "Run this command:"
echo ""
echo "    php artisan bank:process-files"
echo ""
read -p "Press ENTER after running above command..."

# STEP 2: Choose activation method
echo ""
echo "STEP 2️⃣ : CHOOSE ACTIVATION METHOD"
echo ""
echo "Option A: CRON (Recommended for most setups)"
echo "  - Run: crontab -e"
echo "  - Add: * * * * * cd /var/www/bankpayment && php artisan schedule:run >> /dev/null 2>&1"
echo "  - Save and exit"
echo ""
echo "Option B: SUPERVISOR (For always-on daemon)"
echo "  - Create file: sudo nano /etc/supervisor/conf.d/bankpay-scheduler.conf"
echo "  - Paste config from BANK_SCHEDULER_SETUP.md"
echo "  - Run:"
echo "      sudo supervisorctl reread"
echo "      sudo supervisorctl update"
echo "      sudo supervisorctl start bankpay-scheduler"
echo ""
read -p "Which option? (A=Cron, B=Supervisor, or press ENTER to skip): " activation

# STEP 3: Test files
echo ""
echo "STEP 3️⃣ : TEST WITH SAMPLE FILES"
echo ""
echo "Run these commands to place test files in inbox:"
echo ""
echo "    cd /var/www/bankpayment"
echo "    echo 'BANK_DATA_LINE_1' > storage/app/bank_files/inbox/test_1.txt"
echo "    echo 'BANK_DATA_LINE_2' > storage/app/bank_files/inbox/test_2.txt"
echo ""
read -p "Press ENTER after creating test files..."

# STEP 4: Run scheduler
echo ""
echo "STEP 4️⃣ : RUN SCHEDULER"
echo ""
echo "Run: php artisan bank:process-files"
echo ""
echo "Expected output:"
echo "  📁 Found 2 file(s) in inbox. Processing..."
echo "  ✓ Processing started: test_1.txt (ID: XXX)"
echo "  ✓ Processing started: test_2.txt (ID: XXX)"
echo ""
read -p "Press ENTER after running scheduler..."

# STEP 5: Check logs
echo ""
echo "STEP 5️⃣ : VERIFY LOGS"
echo ""
echo "Run: tail -10 storage/logs/bank_processing-*.log"
echo ""
echo "You should see entries with:"
echo "  - file_id"
echo "  - file_name"
echo "  - file_hash"
echo ""
read -p "Press ENTER after checking logs..."

# STEP 6: Test duplicate prevention
echo ""
echo "STEP 6️⃣ : TEST DUPLICATE PREVENTION"
echo ""
echo "Run these to create duplicate files:"
echo ""
echo "    echo 'BANK_DATA_LINE_1' > storage/app/bank_files/inbox/test_3.txt"
echo "    php artisan bank:process-files"
echo ""
echo "You should see:"
echo "  ⚠️  Skipped (already processed): test_3.txt"
echo ""
read -p "Press ENTER after testing duplicates..."

# STEP 7: Summary
echo ""
echo "======================================================"
echo "✅ SETUP COMPLETE!"
echo "======================================================"
echo ""
echo "Your scheduler is configured to:"
echo "  ✓ Run every 15 minutes"
echo "  ✓ Scan inbox directory"
echo "  ✓ Detect new files"
echo "  ✓ Prevent duplicate processing"
echo "  ✓ Log all file IDs and names"
echo "  ✓ Track using SHA256 hash"
echo ""
echo "Key files created:"
echo "  - app/Console/Commands/ProcessBankFiles.php"
echo "  - app/Console/Kernel.php"
echo "  - config/bankfiles.php"
echo "  - config/logging.php (updated)"
echo ""
echo "Documentation:"
echo "  - SCHEDULER_SUMMARY.md - Complete overview"
echo "  - BANK_SCHEDULER_SETUP.md - Detailed setup guide"
echo "  - SCHEDULER_CHECKLIST.md - Implementation checklist"
echo ""
echo "Monitor with:"
echo "  tail -f storage/logs/bank_processing-*.log"
echo ""
echo "======================================================"
echo ""
